{"name": "Попытка создания курьера c повторяющимся логином возвращает \"Этот логин уже используется. Попробуйте другой.\"", "status": "passed", "steps": [{"name": "Запрос создания курьера", "status": "passed", "parameters": [{"name": "login", "value": "'ixsezbjpxw'"}, {"name": "password", "value": "'ejaibijili'"}, {"name": "firstname", "value": "'rbjsvzynlk'"}], "start": 1745013319903, "stop": 1745013320235}], "start": 1745013319339, "stop": 1745013320235, "uuid": "33fd8247-13cb-46a1-93e1-a916f066d8eb", "historyId": "129b623fb61dbcbf22e2d65c9e825085", "testCaseId": "129b623fb61dbcbf22e2d65c9e825085", "fullName": "test.test_create_courier.TestCreateCourier#test_signup_double_login_return_fail", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "WM-HY9GFP70WW"}, {"name": "thread", "value": "68803-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_create_courier"}]}